/**
 * Shared authentication for /api/public/marq/* endpoints (Sprint 12).
 *
 * Brand storefronts (generated by Site Builder) call MARQ via API keys
 * minted in `tenant_api_keys`. We never store the raw key — only its
 * SHA-256 hash + a visible prefix. The validator uses a SECURITY DEFINER
 * RPC so the public anon role can't read the table directly.
 *
 * Header convention:
 *   Authorization: Bearer marq_pk_<prefix8>_<secret24>
 *   x-marq-tenant: <tenant uuid>   (defence-in-depth — must match the key's tenant)
 *
 * On success we asynchronously touch `last_used_at` (don't block the request).
 */
import { supabaseAdmin } from "@/integrations/supabase/client.server";

export type AuthorizedKey = {
  tenantId: string;
  tier: "public_readonly" | "public_write" | "server_full";
  scopes: string[];
  keyId: string;
};

export type AuthFailure = { error: string; status: number };

const KEY_REGEX = /^marq_(pk|sk)_([a-zA-Z0-9]{8})_([a-zA-Z0-9]{16,64})$/;

export async function authorizeMarqApiKey(
  request: Request,
  required: { scope?: string; minTier?: AuthorizedKey["tier"] } = {},
): Promise<AuthorizedKey | AuthFailure> {
  const auth = request.headers.get("authorization") ?? "";
  if (!auth.toLowerCase().startsWith("bearer ")) {
    return { error: "Missing bearer token", status: 401 };
  }
  const token = auth.slice(7).trim();
  const m = token.match(KEY_REGEX);
  if (!m) return { error: "Malformed API key", status: 401 };
  const [, , prefix, secret] = m;

  const hash = await sha256Hex(secret);
  const { data, error } = await supabaseAdmin.rpc("validate_tenant_api_key", {
    _prefix: prefix,
    _hash: hash,
  });
  if (error || !data || data.length === 0) {
    return { error: "Invalid or revoked API key", status: 401 };
  }
  const row = data[0] as {
    tenant_id: string;
    tier: AuthorizedKey["tier"];
    scopes: string[];
    key_id: string;
  };

  // Defence-in-depth: brand site MUST also send its tenant id in a header,
  // and it must match the key's tenant. Stops accidental cross-tenant calls.
  const headerTenant = request.headers.get("x-marq-tenant");
  if (headerTenant && headerTenant !== row.tenant_id) {
    return { error: "Tenant mismatch", status: 403 };
  }

  if (required.scope && !row.scopes.includes(required.scope)) {
    return { error: `Missing scope: ${required.scope}`, status: 403 };
  }
  if (required.minTier) {
    const order = { public_readonly: 0, public_write: 1, server_full: 2 } as const;
    if (order[row.tier] < order[required.minTier]) {
      return { error: `Tier '${row.tier}' insufficient`, status: 403 };
    }
  }

  // Fire-and-forget last_used_at update.
  void supabaseAdmin.rpc("touch_tenant_api_key", { _key_id: row.key_id }).then(() => {});

  return {
    tenantId: row.tenant_id,
    tier: row.tier,
    scopes: row.scopes,
    keyId: row.key_id,
  };
}

export function jsonResponse(body: unknown, init: ResponseInit = {}): Response {
  const headers = new Headers(init.headers);
  headers.set("Content-Type", "application/json");
  // CORS — brand storefronts call from any origin.
  headers.set("Access-Control-Allow-Origin", "*");
  headers.set("Access-Control-Allow-Headers", "authorization, content-type, x-marq-tenant");
  headers.set("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  return new Response(JSON.stringify(body), { ...init, headers });
}

export function preflight(): Response {
  return jsonResponse({}, { status: 204 });
}

async function sha256Hex(input: string): Promise<string> {
  const enc = new TextEncoder().encode(input);
  // Copy into a fresh ArrayBuffer for WebCrypto BufferSource typing.
  const ab = new ArrayBuffer(enc.byteLength);
  new Uint8Array(ab).set(enc);
  const buf = await crypto.subtle.digest("SHA-256", ab);
  return Array.from(new Uint8Array(buf))
    .map((b) => b.toString(16).padStart(2, "0"))
    .join("");
}

/**
 * Generate a fresh API key. Returns both the plaintext (shown once to the
 * user) and the prefix + hash to persist.
 */
export async function mintApiKey(kind: "pk" | "sk" = "pk"): Promise<{
  plaintext: string;
  prefix: string;
  hash: string;
}> {
  const prefix = randomBase62(8);
  const secret = randomBase62(32);
  const plaintext = `marq_${kind}_${prefix}_${secret}`;
  const hash = await sha256Hex(secret);
  return { plaintext, prefix, hash };
}

function randomBase62(len: number): string {
  const alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
  const buf = new Uint8Array(len);
  crypto.getRandomValues(buf);
  let out = "";
  for (let i = 0; i < len; i++) out += alphabet[buf[i] % alphabet.length];
  return out;
}
