/**
 * Brand-aware text templates used to populate the generated ZIP archive
 * (Sprint 11.5).
 *
 * Pure functions — no Supabase / fs access here. All inputs come from
 * `SafeBrandContext`. Each template returns a UTF-8 string ready to be
 * written into a JSZip entry.
 */
import type { SafeBrandContext } from "./brandContext";

export function brandReadme(ctx: SafeBrandContext): string {
  const { profile, template } = ctx;
  return `# ${profile.brand_name} — Brand Site Kit

Generated by MARQ Site Builder (template: **${template.name}**, key: \`${template.key}\`).

This archive contains everything you need to spin up a standalone copy of the
"My Food Diary" storefront, rebranded for your business. Two paths:

## Option A — Remix the source project on Lovable

1. Open the source project: https://lovable.dev/projects/${template.source_project_id ?? "<source-project-id>"}
2. Click ⋯ → **Remix**.
3. In the new project, replace the brand assets with the contents of \`assets/\`.
4. Replace \`src/index.css\` color tokens with the values in \`theme.css\`.
5. Replace \`index.html\` head metadata with \`index.html\` from this archive.
6. Update environment variables: copy \`.env.example\` → \`.env\`, fill in your
   own Supabase URL + anon key (do **not** reuse the MARQ project credentials).
7. \`npm install && npm run build\` → deploy via Lovable Publish.

## Option B — Run locally

\`\`\`bash
unzip ${slug(profile.brand_name)}-site-kit.zip
cd ${slug(profile.brand_name)}-site-kit/integration
# Apply theme.css over your fork of the template
# Then build & deploy as usual
\`\`\`

## What is included

- \`BRAND.md\` — copy, contacts, palette, fonts (single source of truth for the rebrand)
- \`theme.css\` — drop-in OKLCH tokens for \`src/index.css\`
- \`index.html\` — pre-rebranded \`<head>\` with SEO + OG tags
- \`manifest.webmanifest\` — PWA manifest with brand colors & name
- \`package.json\` — minimal package metadata pre-filled with brand name
- \`.env.example\` — environment placeholders (no MARQ secrets)
- \`assets/README.md\` — instructions for placing logo / favicon / OG image

## What is NOT included (intentionally)

For security, the archive does **not** include any MARQ secrets, payment
gateway private keys, Resend API key, Supabase service-role key, Telegram
webhook secret, or files under \`.lovable/\`. You must provision your own
infrastructure for the rebranded site.

---
Generated at: ${new Date().toISOString()}
Source commit: ${template.source_commit ?? "n/a"}
`;
}

export function brandMarkdown(ctx: SafeBrandContext): string {
  const { profile } = ctx;
  return `# Brand Profile

## Identity
- **Name**: ${profile.brand_name}
- **Tagline**: ${profile.tagline || "_not set_"}
- **Description**: ${profile.description || "_not set_"}

## Theme
- **Primary color**: \`${profile.primary_color}\`
- **Accent color**: \`${profile.accent_color}\`
- **Font family**: ${profile.font_family}

## Contacts
- **Email**: ${profile.contact_email || "_not set_"}
- **Phone**: ${profile.contact_phone || "_not set_"}
- **Address**: ${profile.address || "_not set_"}
- **Legal entity**: ${profile.legal_entity || "_not set_"}

## Locale & currency
- **Locale**: ${profile.locale}
- **Currency**: ${profile.currency}

## Domains
- **Custom domain**: ${profile.custom_domain || "_not set_"}

## Hero copy
${profile.hero_copy || "_(empty — fill in before launch)_"}

## About copy
${profile.about_copy || "_(empty — fill in before launch)_"}

## Social links
${
  Object.keys(profile.social_links).length
    ? Object.entries(profile.social_links)
        .map(([k, v]) => `- **${k}**: ${String(v)}`)
        .join("\n")
    : "_none configured_"
}
`;
}

export function themeCss(ctx: SafeBrandContext): string {
  const { profile } = ctx;
  return `/**
 * Brand theme tokens for ${profile.brand_name}
 * Generated by MARQ Site Builder. Drop into src/index.css under :root and .dark.
 */
:root {
  --brand-primary: ${profile.primary_color};
  --brand-accent: ${profile.accent_color};
  --brand-font: "${profile.font_family}", system-ui, -apple-system, sans-serif;

  /* shadcn-compatible mapping (overrides). */
  --primary: ${profile.primary_color};
  --accent: ${profile.accent_color};
  --ring: ${profile.primary_color};
}

.dark {
  --brand-primary: ${profile.primary_color};
  --brand-accent: ${profile.accent_color};
}

body {
  font-family: var(--brand-font);
}
`;
}

export function indexHtml(ctx: SafeBrandContext): string {
  const { profile } = ctx;
  const title = profile.tagline
    ? `${profile.brand_name} — ${profile.tagline}`
    : profile.brand_name;
  const desc = profile.description || profile.tagline || profile.brand_name;
  const ogImage = profile.og_image_url || "";
  const lang = profile.locale === "en" ? "en" : "uk";
  return `<!doctype html>
<html lang="${escapeHtml(lang)}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${escapeHtml(title)}</title>
    <meta name="description" content="${escapeHtml(desc)}" />
    <meta name="theme-color" content="${profile.primary_color.startsWith("#") ? profile.primary_color : "#1a1410"}" />

    ${profile.favicon_url ? `<link rel="icon" href="${escapeAttr(profile.favicon_url)}" />` : "<!-- favicon: add /favicon.ico -->"}
    ${profile.logo_url ? `<link rel="apple-touch-icon" href="${escapeAttr(profile.logo_url)}" />` : ""}
    <link rel="manifest" href="/manifest.webmanifest" />

    <meta property="og:title" content="${escapeHtml(title)}" />
    <meta property="og:description" content="${escapeHtml(desc)}" />
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="${escapeHtml(profile.brand_name)}" />
    <meta property="og:locale" content="${escapeAttr(lang === "en" ? "en_US" : "uk_UA")}" />
    ${ogImage ? `<meta property="og:image" content="${escapeAttr(ogImage)}" />` : ""}

    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${escapeHtml(title)}" />
    <meta name="twitter:description" content="${escapeHtml(desc)}" />
    ${ogImage ? `<meta name="twitter:image" content="${escapeAttr(ogImage)}" />` : ""}
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
`;
}

export function manifestWebmanifest(ctx: SafeBrandContext): string {
  const { profile } = ctx;
  return JSON.stringify(
    {
      name: profile.brand_name,
      short_name: profile.brand_name.slice(0, 12),
      description: profile.description || profile.tagline || profile.brand_name,
      start_url: "/",
      display: "standalone",
      background_color: "#ffffff",
      theme_color: profile.primary_color.startsWith("#") ? profile.primary_color : "#1a1410",
      icons: [
        ...(profile.favicon_url
          ? [{ src: profile.favicon_url, sizes: "192x192", type: "image/png" }]
          : []),
        ...(profile.logo_url
          ? [{ src: profile.logo_url, sizes: "512x512", type: "image/png" }]
          : []),
      ],
    },
    null,
    2,
  );
}

export function packageJson(ctx: SafeBrandContext): string {
  return JSON.stringify(
    {
      name: slug(ctx.profile.brand_name) + "-site",
      private: true,
      version: "0.1.0",
      type: "module",
      description:
        ctx.profile.description ||
        `${ctx.profile.brand_name} storefront, generated by MARQ from template ${ctx.template.key}.`,
      scripts: {
        dev: "vite",
        build: "vite build",
        preview: "vite preview",
      },
    },
    null,
    2,
  );
}

export function envExample(ctx: SafeBrandContext): string {
  return `# Environment variables for ${ctx.profile.brand_name}
# DO NOT commit this file once filled in.

# === Your own Lovable Cloud / Supabase project ===
VITE_SUPABASE_URL=https://your-project-ref.supabase.co
VITE_SUPABASE_PUBLISHABLE_KEY=your-public-anon-key

# === MARQ Shared Engine (powers all 86 ACOS agents) ===
# Get these from your MARQ dashboard → Brand → Site Builder → "Generate API key".
# The key is shown ONCE — copy it immediately.
VITE_MARQ_API_BASE=https://e-marq.lovable.app
VITE_MARQ_TENANT_ID=${ctx.tenant.id}
VITE_MARQ_PUBLIC_KEY=marq_pk_xxxxxxxx_xxxxxxxxxxxxxxxxxxxxxxxx

# === Optional: payment gateways (your own merchant accounts) ===
# LIQPAY_PUBLIC_KEY=
# LIQPAY_PRIVATE_KEY=
# WAYFORPAY_MERCHANT_ACCOUNT=
# WAYFORPAY_MERCHANT_SECRET=
# MONOBANK_TOKEN=
`;
}

export function assetsReadme(ctx: SafeBrandContext): string {
  const lines: string[] = [
    `# Assets for ${ctx.profile.brand_name}`,
    "",
    "Place the following image files in this folder before deploying:",
    "",
  ];
  if (ctx.profile.logo_url) lines.push(`- \`logo.png\` (downloaded from: ${ctx.profile.logo_url})`);
  else lines.push("- `logo.png` — your brand logo (recommended 512×512)");
  if (ctx.profile.favicon_url)
    lines.push(`- \`favicon.png\` (downloaded from: ${ctx.profile.favicon_url})`);
  else lines.push("- `favicon.png` — favicon (recommended 192×192)");
  if (ctx.profile.og_image_url)
    lines.push(`- \`og-default.jpg\` (downloaded from: ${ctx.profile.og_image_url})`);
  else lines.push("- `og-default.jpg` — social share image (recommended 1200×630)");
  return lines.join("\n") + "\n";
}

/**
 * Full drop-in `src/index.css` for the remixed MFD project.
 *
 * Reproduces the MFD CSS structure (HSL tokens, dark/light themes, utilities,
 * accessibility rules) but swaps `--primary`, `--accent`, `--ring` and the
 * gradient stops for the brand's colors. After remixing the source project,
 * the user replaces their `src/index.css` with this file and the whole
 * storefront re-skins instantly.
 *
 * We keep the surrounding palette (background, card, muted, success, destructive)
 * because they were tuned for WCAG AA over warm cream / dark warm surfaces.
 */
export function fullIndexCss(ctx: SafeBrandContext): string {
  const { profile } = ctx;
  const primary = profile.primary_color;
  const accent = profile.accent_color;
  return `@tailwind base;
@tailwind components;
@tailwind utilities;

/**
 * ${profile.brand_name} — generated by MARQ Site Builder.
 * Drop-in replacement for src/index.css in your remixed MFD project.
 */
@layer base {
  :root,
  .dark {
    --background: 30 12% 7%;
    --foreground: 40 25% 92%;
    --card: 30 10% 11%;
    --card-foreground: 40 20% 92%;
    --popover: 30 10% 11%;
    --popover-foreground: 40 20% 92%;

    --brand-primary: ${primary};
    --brand-accent: ${accent};
    --brand-font: "${profile.font_family}", system-ui, -apple-system, sans-serif;

    --primary: ${primary};
    --primary-foreground: 30 20% 10%;
    --primary-glow: ${accent};

    --secondary: 30 10% 15%;
    --secondary-foreground: 40 20% 92%;
    --muted: 30 10% 15%;
    --muted-foreground: 40 12% 72%;
    --accent: ${accent};
    --accent-foreground: 30 20% 10%;
    --destructive: 0 75% 55%;
    --destructive-foreground: 210 40% 98%;
    --success: 142 65% 45%;
    --success-foreground: 0 0% 100%;
    --border: 30 10% 18%;
    --input: 30 10% 18%;
    --ring: ${primary};
    --radius: 0.75rem;

    --gradient-primary: linear-gradient(135deg, ${primary}, ${accent});
    --gradient-subtle: linear-gradient(180deg, hsl(30 12% 9%), hsl(30 12% 7%));
    --shadow-glow: 0 8px 30px -8px color-mix(in oklab, ${primary} 30%, transparent);
    --shadow-soft: 0 4px 20px -6px hsl(0 0% 0% / 0.4);
    --transition-smooth: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);

    --sidebar-background: 30 10% 8%;
    --sidebar-foreground: 40 20% 90%;
    --sidebar-primary: ${primary};
    --sidebar-primary-foreground: 30 10% 8%;
    --sidebar-accent: 30 10% 16%;
    --sidebar-accent-foreground: 40 20% 90%;
    --sidebar-border: 30 10% 20%;
    --sidebar-ring: ${primary};
  }

  .light {
    --background: 36 32% 88%;
    --foreground: 28 45% 9%;
    --card: 36 30% 93%;
    --card-foreground: 28 45% 9%;
    --popover: 36 30% 95%;
    --popover-foreground: 28 45% 9%;
    --primary: ${primary};
    --primary-foreground: 36 40% 98%;
    --primary-glow: ${accent};
    --secondary: 34 25% 82%;
    --secondary-foreground: 28 45% 12%;
    --muted: 34 22% 84%;
    --muted-foreground: 28 25% 28%;
    --accent: ${accent};
    --accent-foreground: 36 40% 98%;
    --destructive: 0 75% 42%;
    --destructive-foreground: 0 0% 100%;
    --success: 142 65% 30%;
    --success-foreground: 0 0% 100%;
    --border: 30 22% 72%;
    --input: 30 22% 72%;
    --ring: ${primary};

    --gradient-primary: linear-gradient(135deg, ${primary}, ${accent});
    --gradient-subtle: linear-gradient(180deg, hsl(36 32% 92%), hsl(36 32% 86%));
    --shadow-glow: 0 8px 30px -8px color-mix(in oklab, ${primary} 30%, transparent);
    --shadow-soft: 0 4px 20px -6px hsl(28 45% 9% / 0.18);

    --sidebar-background: 36 30% 90%;
    --sidebar-foreground: 28 45% 12%;
    --sidebar-primary: ${primary};
    --sidebar-primary-foreground: 36 40% 98%;
    --sidebar-accent: 34 25% 82%;
    --sidebar-accent-foreground: 28 45% 12%;
    --sidebar-border: 30 22% 72%;
    --sidebar-ring: ${primary};
  }
}

@layer base {
  * { @apply border-border; }

  *:focus-visible {
    outline: 2px solid hsl(var(--ring));
    outline-offset: 2px;
    border-radius: 4px;
  }

  @media (prefers-reduced-motion: reduce) {
    *, *::before, *::after {
      animation-duration: 0.01ms !important;
      animation-iteration-count: 1 !important;
      transition-duration: 0.01ms !important;
    }
  }

  html, body, #root { background: transparent !important; }
  body {
    @apply text-foreground;
    background-color: hsl(var(--background));
    overflow-x: hidden;
    text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    font-feature-settings: "kern" 1, "locl" 1;
    line-height: 1.6;
    font-family: var(--brand-font);
  }

  h1, h2, h3, h4, h5, h6 { text-wrap: balance; line-height: 1.2; letter-spacing: -0.01em; }
  p { text-wrap: pretty; line-height: 1.6; }
  img, video { max-width: 100%; height: auto; }
}

html { scroll-behavior: smooth; }

@media (max-width: 639px) {
  .container { padding-left: 1rem !important; padding-right: 1rem !important; }
}

@layer utilities {
  .bg-gradient-primary { background: var(--gradient-primary); }
  .shadow-glow { box-shadow: var(--shadow-glow); }
  .shadow-soft { box-shadow: var(--shadow-soft); }
  .transition-smooth { transition: var(--transition-smooth); }
}
`;
}

/**
 * Step-by-step remix guide. The single most important doc in the archive —
 * turns a 30 KB overlay into a working basicfood-clone for the user's brand.
 */
export function brandRemixGuide(ctx: SafeBrandContext): string {
  const { profile, template } = ctx;
  const sourceUrl = template.source_project_id
    ? `https://lovable.dev/projects/${template.source_project_id}`
    : "https://basicfood.lovable.app";
  return `# ${profile.brand_name} — Remix & Deploy Guide

Цей архів — **brand-overlay** для шаблону **${template.name}** (${sourceUrl}).
За 10–15 хвилин ви отримаєте працюючий сайт під свій бренд.

## Крок 1 — Remix джерело

1. Відкрийте: ${sourceUrl}
2. Натисніть ⋯ → **Remix**.
3. Назва проекту: \`${slug(profile.brand_name)}-site\`.

## Крок 2 — Підключіть Lovable Cloud

У свіжому реміксі: **Settings → Lovable Cloud → Enable**.
Це створить ВАШ окремий backend. **НЕ** використовуйте ключі MARQ.

## Крок 3 — Замініть бренд-стилі

Відкрийте \`src/index.css\` у реміксі і **повністю замініть** його вмістом
файлу \`src/index.css\` з цього архіву (вже містить ваші кольори:
primary \`${profile.primary_color}\`, accent \`${profile.accent_color}\`).

## Крок 4 — Замініть SEO-метадані

Відкрийте \`index.html\` у реміксі та замініть блок \`<head>\` вмістом
\`index.html\` з архіву.

## Крок 5 — Завантажте логотип і фавікон

Покладіть файли з \`assets/\` (\`logo.png\`, \`favicon.png\`, \`og-default.jpg\`)
у папку \`public/\` ремiксу. Якщо їх немає — попросіть Lovable згенерувати:
«Створи логотип для бренду ${profile.brand_name}».

## Крок 6 — Завантажте контент із seed.json

У чаті Lovable: «Прочитай \`seed.json\` і встав hero-копію на головну,
about-копію в розділ «Про нас», категорії в каталог».

## Крок 7 — Додайте товари

**Backend → products**: вручну або через CSV-імпорт.

## Крок 8 — Налаштуйте платежі (опційно)

Заповніть \`.env\` ключами для LiqPay / WayForPay / Monobank
(шаблон у \`.env.example\`).

## Крок 9 — Опублікуйте

**Publish** у правому верхньому куті. URL: \`https://${slug(profile.brand_name)}-site.lovable.app\`.

## Крок 10 — Кастомний домен (опційно)

${profile.custom_domain
  ? `Ваш домен \`${profile.custom_domain}\` — підключіть у **Settings → Domains**.`
  : `**Settings → Domains** → додайте свій домен і налаштуйте DNS.`}

---

## Заборонено

- ❌ Копіювати секрети з MARQ (Supabase service-role, Resend API key) — у вас має бути ВЛАСНИЙ backend.
- ❌ Редагувати \`src/integrations/supabase/\` — Lovable генерує автоматично.
- ❌ Публікувати \`.env\` у Git.

## Підтримка

- MARQ Handbook — у вашому MARQ-кабінеті.
- Lovable чат — у вашому ремiксі.
`;
}

/**
 * Seed JSON — drop-in content blob the user pastes into Lovable chat to
 * populate the freshly remixed storefront with their actual brand copy.
 */
export function seedJson(ctx: SafeBrandContext): string {
  const { profile } = ctx;
  return JSON.stringify(
    {
      $schema: "https://marq.lovable.app/schemas/site-seed.v1.json",
      brand: {
        name: profile.brand_name,
        tagline: profile.tagline ?? "",
        description: profile.description ?? "",
        locale: profile.locale,
        currency: profile.currency,
      },
      hero: {
        headline: profile.tagline || profile.brand_name,
        subheadline: profile.description || "",
        body: profile.hero_copy || "",
        cta_primary: { label: "Каталог", to: "/catalog" },
        cta_secondary: { label: "Про нас", to: "/about" },
      },
      about: {
        title: `Про ${profile.brand_name}`,
        body: profile.about_copy || profile.description || "",
        legal_entity: profile.legal_entity ?? "",
        address: profile.address ?? "",
      },
      contacts: {
        email: profile.contact_email ?? "",
        phone: profile.contact_phone ?? "",
        social: profile.social_links,
      },
      theme: {
        primary_color: profile.primary_color,
        accent_color: profile.accent_color,
        font_family: profile.font_family,
      },
      product_categories_seed: [
        { handle: "bestsellers", name: "Хіти продажів" },
        { handle: "new", name: "Новинки" },
        { handle: "gifts", name: "Подарункові набори" },
      ],
      legal_pages_defaults: ["privacy", "terms", "shipping", "returns"],
    },
    null,
    2,
  );
}

// ----------------------------------------------------------------------------

function slug(name: string): string {
  return (
    name
      .toLowerCase()
      .normalize("NFKD")
      .replace(/[\u0300-\u036f]/g, "")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 60) || "brand"
  );
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

function escapeAttr(s: string): string {
  return escapeHtml(s);
}
