/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as HooksAgentsChurnRiskRouteImport } from './routes/hooks/agents.churn-risk'
import { Route as AuthenticatedAdminTenantsRouteImport } from './routes/_authenticated/admin.tenants'
import { Route as SSlugOrdersOrderIdRouteImport } from './routes/s.$slug.orders.$orderId'
import { Route as AuthenticatedAdminTenantsTenantIdRouteImport } from './routes/_authenticated/admin.tenants.$tenantId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const HooksAgentsChurnRiskRoute = HooksAgentsChurnRiskRouteImport.update({
  id: '/hooks/agents/churn-risk',
  path: '/hooks/agents/churn-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminTenantsRoute =
  AuthenticatedAdminTenantsRouteImport.update({
    id: '/admin/tenants',
    path: '/admin/tenants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const SSlugOrdersOrderIdRoute = SSlugOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => SSlugRoute,
} as any)
const AuthenticatedAdminTenantsTenantIdRoute =
  AuthenticatedAdminTenantsTenantIdRouteImport.update({
    id: '/$tenantId',
    path: '/$tenantId',
    getParentRoute: () => AuthenticatedAdminTenantsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/admin/tenants': typeof AuthenticatedAdminTenantsRouteWithChildren
  '/hooks/agents/churn-risk': typeof HooksAgentsChurnRiskRoute
  '/admin/tenants/$tenantId': typeof AuthenticatedAdminTenantsTenantIdRoute
  '/s/$slug/orders/$orderId': typeof SSlugOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/admin/tenants': typeof AuthenticatedAdminTenantsRouteWithChildren
  '/hooks/agents/churn-risk': typeof HooksAgentsChurnRiskRoute
  '/admin/tenants/$tenantId': typeof AuthenticatedAdminTenantsTenantIdRoute
  '/s/$slug/orders/$orderId': typeof SSlugOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRouteWithChildren
  '/hooks/agents/churn-risk': typeof HooksAgentsChurnRiskRoute
  '/_authenticated/admin/tenants/$tenantId': typeof AuthenticatedAdminTenantsTenantIdRoute
  '/s/$slug/orders/$orderId': typeof SSlugOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/s/$slug'
    | '/admin/tenants'
    | '/hooks/agents/churn-risk'
    | '/admin/tenants/$tenantId'
    | '/s/$slug/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/s/$slug'
    | '/admin/tenants'
    | '/hooks/agents/churn-risk'
    | '/admin/tenants/$tenantId'
    | '/s/$slug/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/s/$slug'
    | '/_authenticated/admin/tenants'
    | '/hooks/agents/churn-risk'
    | '/_authenticated/admin/tenants/$tenantId'
    | '/s/$slug/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  SSlugRoute: typeof SSlugRouteWithChildren
  HooksAgentsChurnRiskRoute: typeof HooksAgentsChurnRiskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/hooks/agents/churn-risk': {
      id: '/hooks/agents/churn-risk'
      path: '/hooks/agents/churn-risk'
      fullPath: '/hooks/agents/churn-risk'
      preLoaderRoute: typeof HooksAgentsChurnRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/s/$slug/orders/$orderId': {
      id: '/s/$slug/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/s/$slug/orders/$orderId'
      preLoaderRoute: typeof SSlugOrdersOrderIdRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/_authenticated/admin/tenants/$tenantId': {
      id: '/_authenticated/admin/tenants/$tenantId'
      path: '/$tenantId'
      fullPath: '/admin/tenants/$tenantId'
      preLoaderRoute: typeof AuthenticatedAdminTenantsTenantIdRouteImport
      parentRoute: typeof AuthenticatedAdminTenantsRoute
    }
  }
}

interface AuthenticatedAdminTenantsRouteChildren {
  AuthenticatedAdminTenantsTenantIdRoute: typeof AuthenticatedAdminTenantsTenantIdRoute
}

const AuthenticatedAdminTenantsRouteChildren: AuthenticatedAdminTenantsRouteChildren =
  {
    AuthenticatedAdminTenantsTenantIdRoute:
      AuthenticatedAdminTenantsTenantIdRoute,
  }

const AuthenticatedAdminTenantsRouteWithChildren =
  AuthenticatedAdminTenantsRoute._addFileChildren(
    AuthenticatedAdminTenantsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminTenantsRoute: typeof AuthenticatedAdminTenantsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminTenantsRoute: AuthenticatedAdminTenantsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SSlugRouteChildren {
  SSlugOrdersOrderIdRoute: typeof SSlugOrdersOrderIdRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugOrdersOrderIdRoute: SSlugOrdersOrderIdRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  SSlugRoute: SSlugRouteWithChildren,
  HooksAgentsChurnRiskRoute: HooksAgentsChurnRiskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
