/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as HooksIngestRouteImport } from './routes/hooks/ingest'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBrandRouteImport } from './routes/_authenticated/brand'
import { Route as TrackSlugJsRouteImport } from './routes/track.$slug.js'
import { Route as HooksTelegramPollRouteImport } from './routes/hooks/telegram.poll'
import { Route as HooksEnginesWinbackOneRouteImport } from './routes/hooks/engines.winback-one'
import { Route as HooksEnginesWinbackAllRouteImport } from './routes/hooks/engines.winback-all'
import { Route as HooksEnginesWinbackRouteImport } from './routes/hooks/engines.winback'
import { Route as HooksEnginesReorderAllRouteImport } from './routes/hooks/engines.reorder-all'
import { Route as HooksEnginesReorderRouteImport } from './routes/hooks/engines.reorder'
import { Route as HooksEnginesDispatchRouteImport } from './routes/hooks/engines.dispatch'
import { Route as HooksEnginesAbandonedCartAllRouteImport } from './routes/hooks/engines.abandoned-cart-all'
import { Route as HooksEnginesAbandonedCartRouteImport } from './routes/hooks/engines.abandoned-cart'
import { Route as HooksDemoSeedRouteImport } from './routes/hooks/demo.seed'
import { Route as HooksAgentsTickRouteImport } from './routes/hooks/agents.tick'
import { Route as HooksAgentsStockoutRouteImport } from './routes/hooks/agents.stockout'
import { Route as HooksAgentsSegmentationRouteImport } from './routes/hooks/agents.segmentation'
import { Route as HooksAgentsSecondOrderNurtureRouteImport } from './routes/hooks/agents.second-order-nurture'
import { Route as HooksAgentsSearchGapRouteImport } from './routes/hooks/agents.search-gap'
import { Route as HooksAgentsSalesBotAllRouteImport } from './routes/hooks/agents.sales-bot-all'
import { Route as HooksAgentsSalesBotRouteImport } from './routes/hooks/agents.sales-bot'
import { Route as HooksAgentsRunAllRouteImport } from './routes/hooks/agents.run-all'
import { Route as HooksAgentsPromoPortfolioRouteImport } from './routes/hooks/agents.promo-portfolio'
import { Route as HooksAgentsPromoFatigueRouteImport } from './routes/hooks/agents.promo-fatigue'
import { Route as HooksAgentsPriceRevertRouteImport } from './routes/hooks/agents.price-revert'
import { Route as HooksAgentsPriceOptimizerRouteImport } from './routes/hooks/agents.price-optimizer'
import { Route as HooksAgentsPredictivePricingRouteImport } from './routes/hooks/agents.predictive-pricing'
import { Route as HooksAgentsOnboardingRouteImport } from './routes/hooks/agents.onboarding'
import { Route as HooksAgentsMorningBriefRouteImport } from './routes/hooks/agents.morning-brief'
import { Route as HooksAgentsMemoryFeedbackRouteImport } from './routes/hooks/agents.memory-feedback'
import { Route as HooksAgentsMarginOptimizerRouteImport } from './routes/hooks/agents.margin-optimizer'
import { Route as HooksAgentsLtvPredictorRouteImport } from './routes/hooks/agents.ltv-predictor'
import { Route as HooksAgentsFunnelHealerRouteImport } from './routes/hooks/agents.funnel-healer'
import { Route as HooksAgentsFeedbackLoopAllRouteImport } from './routes/hooks/agents.feedback-loop-all'
import { Route as HooksAgentsFeedbackLoopRouteImport } from './routes/hooks/agents.feedback-loop'
import { Route as HooksAgentsDiscountElasticityRouteImport } from './routes/hooks/agents.discount-elasticity'
import { Route as HooksAgentsCronAllRouteImport } from './routes/hooks/agents.cron-all'
import { Route as HooksAgentsCohortEngineRouteImport } from './routes/hooks/agents.cohort-engine'
import { Route as HooksAgentsChurnRiskRouteImport } from './routes/hooks/agents.churn-risk'
import { Route as HooksAgentsCartRecoveryRouteImport } from './routes/hooks/agents.cart-recovery'
import { Route as HooksAgentsBundleRecommenderRouteImport } from './routes/hooks/agents.bundle-recommender'
import { Route as HooksAgentsBrowseAbandonmentRouteImport } from './routes/hooks/agents.browse-abandonment'
import { Route as HooksAgentsBotQualityRouteImport } from './routes/hooks/agents.bot-quality'
import { Route as HooksAgentsAttributionRouteImport } from './routes/hooks/agents.attribution'
import { Route as HooksAgentsAovOptimizerRouteImport } from './routes/hooks/agents.aov-optimizer'
import { Route as HooksAgentsAovLeakRouteImport } from './routes/hooks/agents.aov-leak'
import { Route as HooksAgentsAnomalyDetectorRouteImport } from './routes/hooks/agents.anomaly-detector'
import { Route as HooksActionsApplyRouteImport } from './routes/hooks/actions.apply'
import { Route as AuthenticatedAdminTenantsRouteImport } from './routes/_authenticated/admin.tenants'
import { Route as SSlugOrdersOrderIdRouteImport } from './routes/s.$slug.orders.$orderId'
import { Route as AuthenticatedAdminTenantsTenantIdRouteImport } from './routes/_authenticated/admin.tenants.$tenantId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksIngestRoute = HooksIngestRouteImport.update({
  id: '/hooks/ingest',
  path: '/hooks/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBrandRoute = AuthenticatedBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const TrackSlugJsRoute = TrackSlugJsRouteImport.update({
  id: '/track/$slug/js',
  path: '/track/$slug/js',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksTelegramPollRoute = HooksTelegramPollRouteImport.update({
  id: '/hooks/telegram/poll',
  path: '/hooks/telegram/poll',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksEnginesWinbackOneRoute = HooksEnginesWinbackOneRouteImport.update({
  id: '/hooks/engines/winback-one',
  path: '/hooks/engines/winback-one',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksEnginesWinbackAllRoute = HooksEnginesWinbackAllRouteImport.update({
  id: '/hooks/engines/winback-all',
  path: '/hooks/engines/winback-all',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksEnginesWinbackRoute = HooksEnginesWinbackRouteImport.update({
  id: '/hooks/engines/winback',
  path: '/hooks/engines/winback',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksEnginesReorderAllRoute = HooksEnginesReorderAllRouteImport.update({
  id: '/hooks/engines/reorder-all',
  path: '/hooks/engines/reorder-all',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksEnginesReorderRoute = HooksEnginesReorderRouteImport.update({
  id: '/hooks/engines/reorder',
  path: '/hooks/engines/reorder',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksEnginesDispatchRoute = HooksEnginesDispatchRouteImport.update({
  id: '/hooks/engines/dispatch',
  path: '/hooks/engines/dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksEnginesAbandonedCartAllRoute =
  HooksEnginesAbandonedCartAllRouteImport.update({
    id: '/hooks/engines/abandoned-cart-all',
    path: '/hooks/engines/abandoned-cart-all',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksEnginesAbandonedCartRoute =
  HooksEnginesAbandonedCartRouteImport.update({
    id: '/hooks/engines/abandoned-cart',
    path: '/hooks/engines/abandoned-cart',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksDemoSeedRoute = HooksDemoSeedRouteImport.update({
  id: '/hooks/demo/seed',
  path: '/hooks/demo/seed',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsTickRoute = HooksAgentsTickRouteImport.update({
  id: '/hooks/agents/tick',
  path: '/hooks/agents/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsStockoutRoute = HooksAgentsStockoutRouteImport.update({
  id: '/hooks/agents/stockout',
  path: '/hooks/agents/stockout',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsSegmentationRoute = HooksAgentsSegmentationRouteImport.update({
  id: '/hooks/agents/segmentation',
  path: '/hooks/agents/segmentation',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsSecondOrderNurtureRoute =
  HooksAgentsSecondOrderNurtureRouteImport.update({
    id: '/hooks/agents/second-order-nurture',
    path: '/hooks/agents/second-order-nurture',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksAgentsSearchGapRoute = HooksAgentsSearchGapRouteImport.update({
  id: '/hooks/agents/search-gap',
  path: '/hooks/agents/search-gap',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsSalesBotAllRoute = HooksAgentsSalesBotAllRouteImport.update({
  id: '/hooks/agents/sales-bot-all',
  path: '/hooks/agents/sales-bot-all',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsSalesBotRoute = HooksAgentsSalesBotRouteImport.update({
  id: '/hooks/agents/sales-bot',
  path: '/hooks/agents/sales-bot',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsRunAllRoute = HooksAgentsRunAllRouteImport.update({
  id: '/hooks/agents/run-all',
  path: '/hooks/agents/run-all',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsPromoPortfolioRoute =
  HooksAgentsPromoPortfolioRouteImport.update({
    id: '/hooks/agents/promo-portfolio',
    path: '/hooks/agents/promo-portfolio',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksAgentsPromoFatigueRoute = HooksAgentsPromoFatigueRouteImport.update({
  id: '/hooks/agents/promo-fatigue',
  path: '/hooks/agents/promo-fatigue',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsPriceRevertRoute = HooksAgentsPriceRevertRouteImport.update({
  id: '/hooks/agents/price-revert',
  path: '/hooks/agents/price-revert',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsPriceOptimizerRoute =
  HooksAgentsPriceOptimizerRouteImport.update({
    id: '/hooks/agents/price-optimizer',
    path: '/hooks/agents/price-optimizer',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksAgentsPredictivePricingRoute =
  HooksAgentsPredictivePricingRouteImport.update({
    id: '/hooks/agents/predictive-pricing',
    path: '/hooks/agents/predictive-pricing',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksAgentsOnboardingRoute = HooksAgentsOnboardingRouteImport.update({
  id: '/hooks/agents/onboarding',
  path: '/hooks/agents/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsMorningBriefRoute = HooksAgentsMorningBriefRouteImport.update({
  id: '/hooks/agents/morning-brief',
  path: '/hooks/agents/morning-brief',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsMemoryFeedbackRoute =
  HooksAgentsMemoryFeedbackRouteImport.update({
    id: '/hooks/agents/memory-feedback',
    path: '/hooks/agents/memory-feedback',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksAgentsMarginOptimizerRoute =
  HooksAgentsMarginOptimizerRouteImport.update({
    id: '/hooks/agents/margin-optimizer',
    path: '/hooks/agents/margin-optimizer',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksAgentsLtvPredictorRoute = HooksAgentsLtvPredictorRouteImport.update({
  id: '/hooks/agents/ltv-predictor',
  path: '/hooks/agents/ltv-predictor',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsFunnelHealerRoute = HooksAgentsFunnelHealerRouteImport.update({
  id: '/hooks/agents/funnel-healer',
  path: '/hooks/agents/funnel-healer',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsFeedbackLoopAllRoute =
  HooksAgentsFeedbackLoopAllRouteImport.update({
    id: '/hooks/agents/feedback-loop-all',
    path: '/hooks/agents/feedback-loop-all',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksAgentsFeedbackLoopRoute = HooksAgentsFeedbackLoopRouteImport.update({
  id: '/hooks/agents/feedback-loop',
  path: '/hooks/agents/feedback-loop',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsDiscountElasticityRoute =
  HooksAgentsDiscountElasticityRouteImport.update({
    id: '/hooks/agents/discount-elasticity',
    path: '/hooks/agents/discount-elasticity',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksAgentsCronAllRoute = HooksAgentsCronAllRouteImport.update({
  id: '/hooks/agents/cron-all',
  path: '/hooks/agents/cron-all',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsCohortEngineRoute = HooksAgentsCohortEngineRouteImport.update({
  id: '/hooks/agents/cohort-engine',
  path: '/hooks/agents/cohort-engine',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsChurnRiskRoute = HooksAgentsChurnRiskRouteImport.update({
  id: '/hooks/agents/churn-risk',
  path: '/hooks/agents/churn-risk',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsCartRecoveryRoute = HooksAgentsCartRecoveryRouteImport.update({
  id: '/hooks/agents/cart-recovery',
  path: '/hooks/agents/cart-recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsBundleRecommenderRoute =
  HooksAgentsBundleRecommenderRouteImport.update({
    id: '/hooks/agents/bundle-recommender',
    path: '/hooks/agents/bundle-recommender',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksAgentsBrowseAbandonmentRoute =
  HooksAgentsBrowseAbandonmentRouteImport.update({
    id: '/hooks/agents/browse-abandonment',
    path: '/hooks/agents/browse-abandonment',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksAgentsBotQualityRoute = HooksAgentsBotQualityRouteImport.update({
  id: '/hooks/agents/bot-quality',
  path: '/hooks/agents/bot-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsAttributionRoute = HooksAgentsAttributionRouteImport.update({
  id: '/hooks/agents/attribution',
  path: '/hooks/agents/attribution',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsAovOptimizerRoute = HooksAgentsAovOptimizerRouteImport.update({
  id: '/hooks/agents/aov-optimizer',
  path: '/hooks/agents/aov-optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsAovLeakRoute = HooksAgentsAovLeakRouteImport.update({
  id: '/hooks/agents/aov-leak',
  path: '/hooks/agents/aov-leak',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksAgentsAnomalyDetectorRoute =
  HooksAgentsAnomalyDetectorRouteImport.update({
    id: '/hooks/agents/anomaly-detector',
    path: '/hooks/agents/anomaly-detector',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksActionsApplyRoute = HooksActionsApplyRouteImport.update({
  id: '/hooks/actions/apply',
  path: '/hooks/actions/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminTenantsRoute =
  AuthenticatedAdminTenantsRouteImport.update({
    id: '/admin/tenants',
    path: '/admin/tenants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const SSlugOrdersOrderIdRoute = SSlugOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => SSlugRoute,
} as any)
const AuthenticatedAdminTenantsTenantIdRoute =
  AuthenticatedAdminTenantsTenantIdRouteImport.update({
    id: '/$tenantId',
    path: '/$tenantId',
    getParentRoute: () => AuthenticatedAdminTenantsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/brand': typeof AuthenticatedBrandRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/hooks/ingest': typeof HooksIngestRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/admin/tenants': typeof AuthenticatedAdminTenantsRouteWithChildren
  '/hooks/actions/apply': typeof HooksActionsApplyRoute
  '/hooks/agents/anomaly-detector': typeof HooksAgentsAnomalyDetectorRoute
  '/hooks/agents/aov-leak': typeof HooksAgentsAovLeakRoute
  '/hooks/agents/aov-optimizer': typeof HooksAgentsAovOptimizerRoute
  '/hooks/agents/attribution': typeof HooksAgentsAttributionRoute
  '/hooks/agents/bot-quality': typeof HooksAgentsBotQualityRoute
  '/hooks/agents/browse-abandonment': typeof HooksAgentsBrowseAbandonmentRoute
  '/hooks/agents/bundle-recommender': typeof HooksAgentsBundleRecommenderRoute
  '/hooks/agents/cart-recovery': typeof HooksAgentsCartRecoveryRoute
  '/hooks/agents/churn-risk': typeof HooksAgentsChurnRiskRoute
  '/hooks/agents/cohort-engine': typeof HooksAgentsCohortEngineRoute
  '/hooks/agents/cron-all': typeof HooksAgentsCronAllRoute
  '/hooks/agents/discount-elasticity': typeof HooksAgentsDiscountElasticityRoute
  '/hooks/agents/feedback-loop': typeof HooksAgentsFeedbackLoopRoute
  '/hooks/agents/feedback-loop-all': typeof HooksAgentsFeedbackLoopAllRoute
  '/hooks/agents/funnel-healer': typeof HooksAgentsFunnelHealerRoute
  '/hooks/agents/ltv-predictor': typeof HooksAgentsLtvPredictorRoute
  '/hooks/agents/margin-optimizer': typeof HooksAgentsMarginOptimizerRoute
  '/hooks/agents/memory-feedback': typeof HooksAgentsMemoryFeedbackRoute
  '/hooks/agents/morning-brief': typeof HooksAgentsMorningBriefRoute
  '/hooks/agents/onboarding': typeof HooksAgentsOnboardingRoute
  '/hooks/agents/predictive-pricing': typeof HooksAgentsPredictivePricingRoute
  '/hooks/agents/price-optimizer': typeof HooksAgentsPriceOptimizerRoute
  '/hooks/agents/price-revert': typeof HooksAgentsPriceRevertRoute
  '/hooks/agents/promo-fatigue': typeof HooksAgentsPromoFatigueRoute
  '/hooks/agents/promo-portfolio': typeof HooksAgentsPromoPortfolioRoute
  '/hooks/agents/run-all': typeof HooksAgentsRunAllRoute
  '/hooks/agents/sales-bot': typeof HooksAgentsSalesBotRoute
  '/hooks/agents/sales-bot-all': typeof HooksAgentsSalesBotAllRoute
  '/hooks/agents/search-gap': typeof HooksAgentsSearchGapRoute
  '/hooks/agents/second-order-nurture': typeof HooksAgentsSecondOrderNurtureRoute
  '/hooks/agents/segmentation': typeof HooksAgentsSegmentationRoute
  '/hooks/agents/stockout': typeof HooksAgentsStockoutRoute
  '/hooks/agents/tick': typeof HooksAgentsTickRoute
  '/hooks/demo/seed': typeof HooksDemoSeedRoute
  '/hooks/engines/abandoned-cart': typeof HooksEnginesAbandonedCartRoute
  '/hooks/engines/abandoned-cart-all': typeof HooksEnginesAbandonedCartAllRoute
  '/hooks/engines/dispatch': typeof HooksEnginesDispatchRoute
  '/hooks/engines/reorder': typeof HooksEnginesReorderRoute
  '/hooks/engines/reorder-all': typeof HooksEnginesReorderAllRoute
  '/hooks/engines/winback': typeof HooksEnginesWinbackRoute
  '/hooks/engines/winback-all': typeof HooksEnginesWinbackAllRoute
  '/hooks/engines/winback-one': typeof HooksEnginesWinbackOneRoute
  '/hooks/telegram/poll': typeof HooksTelegramPollRoute
  '/track/$slug/js': typeof TrackSlugJsRoute
  '/admin/tenants/$tenantId': typeof AuthenticatedAdminTenantsTenantIdRoute
  '/s/$slug/orders/$orderId': typeof SSlugOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/brand': typeof AuthenticatedBrandRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/hooks/ingest': typeof HooksIngestRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/admin/tenants': typeof AuthenticatedAdminTenantsRouteWithChildren
  '/hooks/actions/apply': typeof HooksActionsApplyRoute
  '/hooks/agents/anomaly-detector': typeof HooksAgentsAnomalyDetectorRoute
  '/hooks/agents/aov-leak': typeof HooksAgentsAovLeakRoute
  '/hooks/agents/aov-optimizer': typeof HooksAgentsAovOptimizerRoute
  '/hooks/agents/attribution': typeof HooksAgentsAttributionRoute
  '/hooks/agents/bot-quality': typeof HooksAgentsBotQualityRoute
  '/hooks/agents/browse-abandonment': typeof HooksAgentsBrowseAbandonmentRoute
  '/hooks/agents/bundle-recommender': typeof HooksAgentsBundleRecommenderRoute
  '/hooks/agents/cart-recovery': typeof HooksAgentsCartRecoveryRoute
  '/hooks/agents/churn-risk': typeof HooksAgentsChurnRiskRoute
  '/hooks/agents/cohort-engine': typeof HooksAgentsCohortEngineRoute
  '/hooks/agents/cron-all': typeof HooksAgentsCronAllRoute
  '/hooks/agents/discount-elasticity': typeof HooksAgentsDiscountElasticityRoute
  '/hooks/agents/feedback-loop': typeof HooksAgentsFeedbackLoopRoute
  '/hooks/agents/feedback-loop-all': typeof HooksAgentsFeedbackLoopAllRoute
  '/hooks/agents/funnel-healer': typeof HooksAgentsFunnelHealerRoute
  '/hooks/agents/ltv-predictor': typeof HooksAgentsLtvPredictorRoute
  '/hooks/agents/margin-optimizer': typeof HooksAgentsMarginOptimizerRoute
  '/hooks/agents/memory-feedback': typeof HooksAgentsMemoryFeedbackRoute
  '/hooks/agents/morning-brief': typeof HooksAgentsMorningBriefRoute
  '/hooks/agents/onboarding': typeof HooksAgentsOnboardingRoute
  '/hooks/agents/predictive-pricing': typeof HooksAgentsPredictivePricingRoute
  '/hooks/agents/price-optimizer': typeof HooksAgentsPriceOptimizerRoute
  '/hooks/agents/price-revert': typeof HooksAgentsPriceRevertRoute
  '/hooks/agents/promo-fatigue': typeof HooksAgentsPromoFatigueRoute
  '/hooks/agents/promo-portfolio': typeof HooksAgentsPromoPortfolioRoute
  '/hooks/agents/run-all': typeof HooksAgentsRunAllRoute
  '/hooks/agents/sales-bot': typeof HooksAgentsSalesBotRoute
  '/hooks/agents/sales-bot-all': typeof HooksAgentsSalesBotAllRoute
  '/hooks/agents/search-gap': typeof HooksAgentsSearchGapRoute
  '/hooks/agents/second-order-nurture': typeof HooksAgentsSecondOrderNurtureRoute
  '/hooks/agents/segmentation': typeof HooksAgentsSegmentationRoute
  '/hooks/agents/stockout': typeof HooksAgentsStockoutRoute
  '/hooks/agents/tick': typeof HooksAgentsTickRoute
  '/hooks/demo/seed': typeof HooksDemoSeedRoute
  '/hooks/engines/abandoned-cart': typeof HooksEnginesAbandonedCartRoute
  '/hooks/engines/abandoned-cart-all': typeof HooksEnginesAbandonedCartAllRoute
  '/hooks/engines/dispatch': typeof HooksEnginesDispatchRoute
  '/hooks/engines/reorder': typeof HooksEnginesReorderRoute
  '/hooks/engines/reorder-all': typeof HooksEnginesReorderAllRoute
  '/hooks/engines/winback': typeof HooksEnginesWinbackRoute
  '/hooks/engines/winback-all': typeof HooksEnginesWinbackAllRoute
  '/hooks/engines/winback-one': typeof HooksEnginesWinbackOneRoute
  '/hooks/telegram/poll': typeof HooksTelegramPollRoute
  '/track/$slug/js': typeof TrackSlugJsRoute
  '/admin/tenants/$tenantId': typeof AuthenticatedAdminTenantsTenantIdRoute
  '/s/$slug/orders/$orderId': typeof SSlugOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/agents': typeof AgentsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/signup': typeof SignupRoute
  '/_authenticated/brand': typeof AuthenticatedBrandRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/hooks/ingest': typeof HooksIngestRoute
  '/s/$slug': typeof SSlugRouteWithChildren
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRouteWithChildren
  '/hooks/actions/apply': typeof HooksActionsApplyRoute
  '/hooks/agents/anomaly-detector': typeof HooksAgentsAnomalyDetectorRoute
  '/hooks/agents/aov-leak': typeof HooksAgentsAovLeakRoute
  '/hooks/agents/aov-optimizer': typeof HooksAgentsAovOptimizerRoute
  '/hooks/agents/attribution': typeof HooksAgentsAttributionRoute
  '/hooks/agents/bot-quality': typeof HooksAgentsBotQualityRoute
  '/hooks/agents/browse-abandonment': typeof HooksAgentsBrowseAbandonmentRoute
  '/hooks/agents/bundle-recommender': typeof HooksAgentsBundleRecommenderRoute
  '/hooks/agents/cart-recovery': typeof HooksAgentsCartRecoveryRoute
  '/hooks/agents/churn-risk': typeof HooksAgentsChurnRiskRoute
  '/hooks/agents/cohort-engine': typeof HooksAgentsCohortEngineRoute
  '/hooks/agents/cron-all': typeof HooksAgentsCronAllRoute
  '/hooks/agents/discount-elasticity': typeof HooksAgentsDiscountElasticityRoute
  '/hooks/agents/feedback-loop': typeof HooksAgentsFeedbackLoopRoute
  '/hooks/agents/feedback-loop-all': typeof HooksAgentsFeedbackLoopAllRoute
  '/hooks/agents/funnel-healer': typeof HooksAgentsFunnelHealerRoute
  '/hooks/agents/ltv-predictor': typeof HooksAgentsLtvPredictorRoute
  '/hooks/agents/margin-optimizer': typeof HooksAgentsMarginOptimizerRoute
  '/hooks/agents/memory-feedback': typeof HooksAgentsMemoryFeedbackRoute
  '/hooks/agents/morning-brief': typeof HooksAgentsMorningBriefRoute
  '/hooks/agents/onboarding': typeof HooksAgentsOnboardingRoute
  '/hooks/agents/predictive-pricing': typeof HooksAgentsPredictivePricingRoute
  '/hooks/agents/price-optimizer': typeof HooksAgentsPriceOptimizerRoute
  '/hooks/agents/price-revert': typeof HooksAgentsPriceRevertRoute
  '/hooks/agents/promo-fatigue': typeof HooksAgentsPromoFatigueRoute
  '/hooks/agents/promo-portfolio': typeof HooksAgentsPromoPortfolioRoute
  '/hooks/agents/run-all': typeof HooksAgentsRunAllRoute
  '/hooks/agents/sales-bot': typeof HooksAgentsSalesBotRoute
  '/hooks/agents/sales-bot-all': typeof HooksAgentsSalesBotAllRoute
  '/hooks/agents/search-gap': typeof HooksAgentsSearchGapRoute
  '/hooks/agents/second-order-nurture': typeof HooksAgentsSecondOrderNurtureRoute
  '/hooks/agents/segmentation': typeof HooksAgentsSegmentationRoute
  '/hooks/agents/stockout': typeof HooksAgentsStockoutRoute
  '/hooks/agents/tick': typeof HooksAgentsTickRoute
  '/hooks/demo/seed': typeof HooksDemoSeedRoute
  '/hooks/engines/abandoned-cart': typeof HooksEnginesAbandonedCartRoute
  '/hooks/engines/abandoned-cart-all': typeof HooksEnginesAbandonedCartAllRoute
  '/hooks/engines/dispatch': typeof HooksEnginesDispatchRoute
  '/hooks/engines/reorder': typeof HooksEnginesReorderRoute
  '/hooks/engines/reorder-all': typeof HooksEnginesReorderAllRoute
  '/hooks/engines/winback': typeof HooksEnginesWinbackRoute
  '/hooks/engines/winback-all': typeof HooksEnginesWinbackAllRoute
  '/hooks/engines/winback-one': typeof HooksEnginesWinbackOneRoute
  '/hooks/telegram/poll': typeof HooksTelegramPollRoute
  '/track/$slug/js': typeof TrackSlugJsRoute
  '/_authenticated/admin/tenants/$tenantId': typeof AuthenticatedAdminTenantsTenantIdRoute
  '/s/$slug/orders/$orderId': typeof SSlugOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/brand'
    | '/dashboard'
    | '/onboarding'
    | '/hooks/ingest'
    | '/s/$slug'
    | '/admin/tenants'
    | '/hooks/actions/apply'
    | '/hooks/agents/anomaly-detector'
    | '/hooks/agents/aov-leak'
    | '/hooks/agents/aov-optimizer'
    | '/hooks/agents/attribution'
    | '/hooks/agents/bot-quality'
    | '/hooks/agents/browse-abandonment'
    | '/hooks/agents/bundle-recommender'
    | '/hooks/agents/cart-recovery'
    | '/hooks/agents/churn-risk'
    | '/hooks/agents/cohort-engine'
    | '/hooks/agents/cron-all'
    | '/hooks/agents/discount-elasticity'
    | '/hooks/agents/feedback-loop'
    | '/hooks/agents/feedback-loop-all'
    | '/hooks/agents/funnel-healer'
    | '/hooks/agents/ltv-predictor'
    | '/hooks/agents/margin-optimizer'
    | '/hooks/agents/memory-feedback'
    | '/hooks/agents/morning-brief'
    | '/hooks/agents/onboarding'
    | '/hooks/agents/predictive-pricing'
    | '/hooks/agents/price-optimizer'
    | '/hooks/agents/price-revert'
    | '/hooks/agents/promo-fatigue'
    | '/hooks/agents/promo-portfolio'
    | '/hooks/agents/run-all'
    | '/hooks/agents/sales-bot'
    | '/hooks/agents/sales-bot-all'
    | '/hooks/agents/search-gap'
    | '/hooks/agents/second-order-nurture'
    | '/hooks/agents/segmentation'
    | '/hooks/agents/stockout'
    | '/hooks/agents/tick'
    | '/hooks/demo/seed'
    | '/hooks/engines/abandoned-cart'
    | '/hooks/engines/abandoned-cart-all'
    | '/hooks/engines/dispatch'
    | '/hooks/engines/reorder'
    | '/hooks/engines/reorder-all'
    | '/hooks/engines/winback'
    | '/hooks/engines/winback-all'
    | '/hooks/engines/winback-one'
    | '/hooks/telegram/poll'
    | '/track/$slug/js'
    | '/admin/tenants/$tenantId'
    | '/s/$slug/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/brand'
    | '/dashboard'
    | '/onboarding'
    | '/hooks/ingest'
    | '/s/$slug'
    | '/admin/tenants'
    | '/hooks/actions/apply'
    | '/hooks/agents/anomaly-detector'
    | '/hooks/agents/aov-leak'
    | '/hooks/agents/aov-optimizer'
    | '/hooks/agents/attribution'
    | '/hooks/agents/bot-quality'
    | '/hooks/agents/browse-abandonment'
    | '/hooks/agents/bundle-recommender'
    | '/hooks/agents/cart-recovery'
    | '/hooks/agents/churn-risk'
    | '/hooks/agents/cohort-engine'
    | '/hooks/agents/cron-all'
    | '/hooks/agents/discount-elasticity'
    | '/hooks/agents/feedback-loop'
    | '/hooks/agents/feedback-loop-all'
    | '/hooks/agents/funnel-healer'
    | '/hooks/agents/ltv-predictor'
    | '/hooks/agents/margin-optimizer'
    | '/hooks/agents/memory-feedback'
    | '/hooks/agents/morning-brief'
    | '/hooks/agents/onboarding'
    | '/hooks/agents/predictive-pricing'
    | '/hooks/agents/price-optimizer'
    | '/hooks/agents/price-revert'
    | '/hooks/agents/promo-fatigue'
    | '/hooks/agents/promo-portfolio'
    | '/hooks/agents/run-all'
    | '/hooks/agents/sales-bot'
    | '/hooks/agents/sales-bot-all'
    | '/hooks/agents/search-gap'
    | '/hooks/agents/second-order-nurture'
    | '/hooks/agents/segmentation'
    | '/hooks/agents/stockout'
    | '/hooks/agents/tick'
    | '/hooks/demo/seed'
    | '/hooks/engines/abandoned-cart'
    | '/hooks/engines/abandoned-cart-all'
    | '/hooks/engines/dispatch'
    | '/hooks/engines/reorder'
    | '/hooks/engines/reorder-all'
    | '/hooks/engines/winback'
    | '/hooks/engines/winback-all'
    | '/hooks/engines/winback-one'
    | '/hooks/telegram/poll'
    | '/track/$slug/js'
    | '/admin/tenants/$tenantId'
    | '/s/$slug/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agents'
    | '/how-it-works'
    | '/login'
    | '/pricing'
    | '/signup'
    | '/_authenticated/brand'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/hooks/ingest'
    | '/s/$slug'
    | '/_authenticated/admin/tenants'
    | '/hooks/actions/apply'
    | '/hooks/agents/anomaly-detector'
    | '/hooks/agents/aov-leak'
    | '/hooks/agents/aov-optimizer'
    | '/hooks/agents/attribution'
    | '/hooks/agents/bot-quality'
    | '/hooks/agents/browse-abandonment'
    | '/hooks/agents/bundle-recommender'
    | '/hooks/agents/cart-recovery'
    | '/hooks/agents/churn-risk'
    | '/hooks/agents/cohort-engine'
    | '/hooks/agents/cron-all'
    | '/hooks/agents/discount-elasticity'
    | '/hooks/agents/feedback-loop'
    | '/hooks/agents/feedback-loop-all'
    | '/hooks/agents/funnel-healer'
    | '/hooks/agents/ltv-predictor'
    | '/hooks/agents/margin-optimizer'
    | '/hooks/agents/memory-feedback'
    | '/hooks/agents/morning-brief'
    | '/hooks/agents/onboarding'
    | '/hooks/agents/predictive-pricing'
    | '/hooks/agents/price-optimizer'
    | '/hooks/agents/price-revert'
    | '/hooks/agents/promo-fatigue'
    | '/hooks/agents/promo-portfolio'
    | '/hooks/agents/run-all'
    | '/hooks/agents/sales-bot'
    | '/hooks/agents/sales-bot-all'
    | '/hooks/agents/search-gap'
    | '/hooks/agents/second-order-nurture'
    | '/hooks/agents/segmentation'
    | '/hooks/agents/stockout'
    | '/hooks/agents/tick'
    | '/hooks/demo/seed'
    | '/hooks/engines/abandoned-cart'
    | '/hooks/engines/abandoned-cart-all'
    | '/hooks/engines/dispatch'
    | '/hooks/engines/reorder'
    | '/hooks/engines/reorder-all'
    | '/hooks/engines/winback'
    | '/hooks/engines/winback-all'
    | '/hooks/engines/winback-one'
    | '/hooks/telegram/poll'
    | '/track/$slug/js'
    | '/_authenticated/admin/tenants/$tenantId'
    | '/s/$slug/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  SignupRoute: typeof SignupRoute
  HooksIngestRoute: typeof HooksIngestRoute
  SSlugRoute: typeof SSlugRouteWithChildren
  HooksActionsApplyRoute: typeof HooksActionsApplyRoute
  HooksAgentsAnomalyDetectorRoute: typeof HooksAgentsAnomalyDetectorRoute
  HooksAgentsAovLeakRoute: typeof HooksAgentsAovLeakRoute
  HooksAgentsAovOptimizerRoute: typeof HooksAgentsAovOptimizerRoute
  HooksAgentsAttributionRoute: typeof HooksAgentsAttributionRoute
  HooksAgentsBotQualityRoute: typeof HooksAgentsBotQualityRoute
  HooksAgentsBrowseAbandonmentRoute: typeof HooksAgentsBrowseAbandonmentRoute
  HooksAgentsBundleRecommenderRoute: typeof HooksAgentsBundleRecommenderRoute
  HooksAgentsCartRecoveryRoute: typeof HooksAgentsCartRecoveryRoute
  HooksAgentsChurnRiskRoute: typeof HooksAgentsChurnRiskRoute
  HooksAgentsCohortEngineRoute: typeof HooksAgentsCohortEngineRoute
  HooksAgentsCronAllRoute: typeof HooksAgentsCronAllRoute
  HooksAgentsDiscountElasticityRoute: typeof HooksAgentsDiscountElasticityRoute
  HooksAgentsFeedbackLoopRoute: typeof HooksAgentsFeedbackLoopRoute
  HooksAgentsFeedbackLoopAllRoute: typeof HooksAgentsFeedbackLoopAllRoute
  HooksAgentsFunnelHealerRoute: typeof HooksAgentsFunnelHealerRoute
  HooksAgentsLtvPredictorRoute: typeof HooksAgentsLtvPredictorRoute
  HooksAgentsMarginOptimizerRoute: typeof HooksAgentsMarginOptimizerRoute
  HooksAgentsMemoryFeedbackRoute: typeof HooksAgentsMemoryFeedbackRoute
  HooksAgentsMorningBriefRoute: typeof HooksAgentsMorningBriefRoute
  HooksAgentsOnboardingRoute: typeof HooksAgentsOnboardingRoute
  HooksAgentsPredictivePricingRoute: typeof HooksAgentsPredictivePricingRoute
  HooksAgentsPriceOptimizerRoute: typeof HooksAgentsPriceOptimizerRoute
  HooksAgentsPriceRevertRoute: typeof HooksAgentsPriceRevertRoute
  HooksAgentsPromoFatigueRoute: typeof HooksAgentsPromoFatigueRoute
  HooksAgentsPromoPortfolioRoute: typeof HooksAgentsPromoPortfolioRoute
  HooksAgentsRunAllRoute: typeof HooksAgentsRunAllRoute
  HooksAgentsSalesBotRoute: typeof HooksAgentsSalesBotRoute
  HooksAgentsSalesBotAllRoute: typeof HooksAgentsSalesBotAllRoute
  HooksAgentsSearchGapRoute: typeof HooksAgentsSearchGapRoute
  HooksAgentsSecondOrderNurtureRoute: typeof HooksAgentsSecondOrderNurtureRoute
  HooksAgentsSegmentationRoute: typeof HooksAgentsSegmentationRoute
  HooksAgentsStockoutRoute: typeof HooksAgentsStockoutRoute
  HooksAgentsTickRoute: typeof HooksAgentsTickRoute
  HooksDemoSeedRoute: typeof HooksDemoSeedRoute
  HooksEnginesAbandonedCartRoute: typeof HooksEnginesAbandonedCartRoute
  HooksEnginesAbandonedCartAllRoute: typeof HooksEnginesAbandonedCartAllRoute
  HooksEnginesDispatchRoute: typeof HooksEnginesDispatchRoute
  HooksEnginesReorderRoute: typeof HooksEnginesReorderRoute
  HooksEnginesReorderAllRoute: typeof HooksEnginesReorderAllRoute
  HooksEnginesWinbackRoute: typeof HooksEnginesWinbackRoute
  HooksEnginesWinbackAllRoute: typeof HooksEnginesWinbackAllRoute
  HooksEnginesWinbackOneRoute: typeof HooksEnginesWinbackOneRoute
  HooksTelegramPollRoute: typeof HooksTelegramPollRoute
  TrackSlugJsRoute: typeof TrackSlugJsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/ingest': {
      id: '/hooks/ingest'
      path: '/hooks/ingest'
      fullPath: '/hooks/ingest'
      preLoaderRoute: typeof HooksIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/brand': {
      id: '/_authenticated/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof AuthenticatedBrandRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/track/$slug/js': {
      id: '/track/$slug/js'
      path: '/track/$slug/js'
      fullPath: '/track/$slug/js'
      preLoaderRoute: typeof TrackSlugJsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/telegram/poll': {
      id: '/hooks/telegram/poll'
      path: '/hooks/telegram/poll'
      fullPath: '/hooks/telegram/poll'
      preLoaderRoute: typeof HooksTelegramPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/engines/winback-one': {
      id: '/hooks/engines/winback-one'
      path: '/hooks/engines/winback-one'
      fullPath: '/hooks/engines/winback-one'
      preLoaderRoute: typeof HooksEnginesWinbackOneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/engines/winback-all': {
      id: '/hooks/engines/winback-all'
      path: '/hooks/engines/winback-all'
      fullPath: '/hooks/engines/winback-all'
      preLoaderRoute: typeof HooksEnginesWinbackAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/engines/winback': {
      id: '/hooks/engines/winback'
      path: '/hooks/engines/winback'
      fullPath: '/hooks/engines/winback'
      preLoaderRoute: typeof HooksEnginesWinbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/engines/reorder-all': {
      id: '/hooks/engines/reorder-all'
      path: '/hooks/engines/reorder-all'
      fullPath: '/hooks/engines/reorder-all'
      preLoaderRoute: typeof HooksEnginesReorderAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/engines/reorder': {
      id: '/hooks/engines/reorder'
      path: '/hooks/engines/reorder'
      fullPath: '/hooks/engines/reorder'
      preLoaderRoute: typeof HooksEnginesReorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/engines/dispatch': {
      id: '/hooks/engines/dispatch'
      path: '/hooks/engines/dispatch'
      fullPath: '/hooks/engines/dispatch'
      preLoaderRoute: typeof HooksEnginesDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/engines/abandoned-cart-all': {
      id: '/hooks/engines/abandoned-cart-all'
      path: '/hooks/engines/abandoned-cart-all'
      fullPath: '/hooks/engines/abandoned-cart-all'
      preLoaderRoute: typeof HooksEnginesAbandonedCartAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/engines/abandoned-cart': {
      id: '/hooks/engines/abandoned-cart'
      path: '/hooks/engines/abandoned-cart'
      fullPath: '/hooks/engines/abandoned-cart'
      preLoaderRoute: typeof HooksEnginesAbandonedCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/demo/seed': {
      id: '/hooks/demo/seed'
      path: '/hooks/demo/seed'
      fullPath: '/hooks/demo/seed'
      preLoaderRoute: typeof HooksDemoSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/tick': {
      id: '/hooks/agents/tick'
      path: '/hooks/agents/tick'
      fullPath: '/hooks/agents/tick'
      preLoaderRoute: typeof HooksAgentsTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/stockout': {
      id: '/hooks/agents/stockout'
      path: '/hooks/agents/stockout'
      fullPath: '/hooks/agents/stockout'
      preLoaderRoute: typeof HooksAgentsStockoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/segmentation': {
      id: '/hooks/agents/segmentation'
      path: '/hooks/agents/segmentation'
      fullPath: '/hooks/agents/segmentation'
      preLoaderRoute: typeof HooksAgentsSegmentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/second-order-nurture': {
      id: '/hooks/agents/second-order-nurture'
      path: '/hooks/agents/second-order-nurture'
      fullPath: '/hooks/agents/second-order-nurture'
      preLoaderRoute: typeof HooksAgentsSecondOrderNurtureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/search-gap': {
      id: '/hooks/agents/search-gap'
      path: '/hooks/agents/search-gap'
      fullPath: '/hooks/agents/search-gap'
      preLoaderRoute: typeof HooksAgentsSearchGapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/sales-bot-all': {
      id: '/hooks/agents/sales-bot-all'
      path: '/hooks/agents/sales-bot-all'
      fullPath: '/hooks/agents/sales-bot-all'
      preLoaderRoute: typeof HooksAgentsSalesBotAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/sales-bot': {
      id: '/hooks/agents/sales-bot'
      path: '/hooks/agents/sales-bot'
      fullPath: '/hooks/agents/sales-bot'
      preLoaderRoute: typeof HooksAgentsSalesBotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/run-all': {
      id: '/hooks/agents/run-all'
      path: '/hooks/agents/run-all'
      fullPath: '/hooks/agents/run-all'
      preLoaderRoute: typeof HooksAgentsRunAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/promo-portfolio': {
      id: '/hooks/agents/promo-portfolio'
      path: '/hooks/agents/promo-portfolio'
      fullPath: '/hooks/agents/promo-portfolio'
      preLoaderRoute: typeof HooksAgentsPromoPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/promo-fatigue': {
      id: '/hooks/agents/promo-fatigue'
      path: '/hooks/agents/promo-fatigue'
      fullPath: '/hooks/agents/promo-fatigue'
      preLoaderRoute: typeof HooksAgentsPromoFatigueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/price-revert': {
      id: '/hooks/agents/price-revert'
      path: '/hooks/agents/price-revert'
      fullPath: '/hooks/agents/price-revert'
      preLoaderRoute: typeof HooksAgentsPriceRevertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/price-optimizer': {
      id: '/hooks/agents/price-optimizer'
      path: '/hooks/agents/price-optimizer'
      fullPath: '/hooks/agents/price-optimizer'
      preLoaderRoute: typeof HooksAgentsPriceOptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/predictive-pricing': {
      id: '/hooks/agents/predictive-pricing'
      path: '/hooks/agents/predictive-pricing'
      fullPath: '/hooks/agents/predictive-pricing'
      preLoaderRoute: typeof HooksAgentsPredictivePricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/onboarding': {
      id: '/hooks/agents/onboarding'
      path: '/hooks/agents/onboarding'
      fullPath: '/hooks/agents/onboarding'
      preLoaderRoute: typeof HooksAgentsOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/morning-brief': {
      id: '/hooks/agents/morning-brief'
      path: '/hooks/agents/morning-brief'
      fullPath: '/hooks/agents/morning-brief'
      preLoaderRoute: typeof HooksAgentsMorningBriefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/memory-feedback': {
      id: '/hooks/agents/memory-feedback'
      path: '/hooks/agents/memory-feedback'
      fullPath: '/hooks/agents/memory-feedback'
      preLoaderRoute: typeof HooksAgentsMemoryFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/margin-optimizer': {
      id: '/hooks/agents/margin-optimizer'
      path: '/hooks/agents/margin-optimizer'
      fullPath: '/hooks/agents/margin-optimizer'
      preLoaderRoute: typeof HooksAgentsMarginOptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/ltv-predictor': {
      id: '/hooks/agents/ltv-predictor'
      path: '/hooks/agents/ltv-predictor'
      fullPath: '/hooks/agents/ltv-predictor'
      preLoaderRoute: typeof HooksAgentsLtvPredictorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/funnel-healer': {
      id: '/hooks/agents/funnel-healer'
      path: '/hooks/agents/funnel-healer'
      fullPath: '/hooks/agents/funnel-healer'
      preLoaderRoute: typeof HooksAgentsFunnelHealerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/feedback-loop-all': {
      id: '/hooks/agents/feedback-loop-all'
      path: '/hooks/agents/feedback-loop-all'
      fullPath: '/hooks/agents/feedback-loop-all'
      preLoaderRoute: typeof HooksAgentsFeedbackLoopAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/feedback-loop': {
      id: '/hooks/agents/feedback-loop'
      path: '/hooks/agents/feedback-loop'
      fullPath: '/hooks/agents/feedback-loop'
      preLoaderRoute: typeof HooksAgentsFeedbackLoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/discount-elasticity': {
      id: '/hooks/agents/discount-elasticity'
      path: '/hooks/agents/discount-elasticity'
      fullPath: '/hooks/agents/discount-elasticity'
      preLoaderRoute: typeof HooksAgentsDiscountElasticityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/cron-all': {
      id: '/hooks/agents/cron-all'
      path: '/hooks/agents/cron-all'
      fullPath: '/hooks/agents/cron-all'
      preLoaderRoute: typeof HooksAgentsCronAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/cohort-engine': {
      id: '/hooks/agents/cohort-engine'
      path: '/hooks/agents/cohort-engine'
      fullPath: '/hooks/agents/cohort-engine'
      preLoaderRoute: typeof HooksAgentsCohortEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/churn-risk': {
      id: '/hooks/agents/churn-risk'
      path: '/hooks/agents/churn-risk'
      fullPath: '/hooks/agents/churn-risk'
      preLoaderRoute: typeof HooksAgentsChurnRiskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/cart-recovery': {
      id: '/hooks/agents/cart-recovery'
      path: '/hooks/agents/cart-recovery'
      fullPath: '/hooks/agents/cart-recovery'
      preLoaderRoute: typeof HooksAgentsCartRecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/bundle-recommender': {
      id: '/hooks/agents/bundle-recommender'
      path: '/hooks/agents/bundle-recommender'
      fullPath: '/hooks/agents/bundle-recommender'
      preLoaderRoute: typeof HooksAgentsBundleRecommenderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/browse-abandonment': {
      id: '/hooks/agents/browse-abandonment'
      path: '/hooks/agents/browse-abandonment'
      fullPath: '/hooks/agents/browse-abandonment'
      preLoaderRoute: typeof HooksAgentsBrowseAbandonmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/bot-quality': {
      id: '/hooks/agents/bot-quality'
      path: '/hooks/agents/bot-quality'
      fullPath: '/hooks/agents/bot-quality'
      preLoaderRoute: typeof HooksAgentsBotQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/attribution': {
      id: '/hooks/agents/attribution'
      path: '/hooks/agents/attribution'
      fullPath: '/hooks/agents/attribution'
      preLoaderRoute: typeof HooksAgentsAttributionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/aov-optimizer': {
      id: '/hooks/agents/aov-optimizer'
      path: '/hooks/agents/aov-optimizer'
      fullPath: '/hooks/agents/aov-optimizer'
      preLoaderRoute: typeof HooksAgentsAovOptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/aov-leak': {
      id: '/hooks/agents/aov-leak'
      path: '/hooks/agents/aov-leak'
      fullPath: '/hooks/agents/aov-leak'
      preLoaderRoute: typeof HooksAgentsAovLeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/agents/anomaly-detector': {
      id: '/hooks/agents/anomaly-detector'
      path: '/hooks/agents/anomaly-detector'
      fullPath: '/hooks/agents/anomaly-detector'
      preLoaderRoute: typeof HooksAgentsAnomalyDetectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/actions/apply': {
      id: '/hooks/actions/apply'
      path: '/hooks/actions/apply'
      fullPath: '/hooks/actions/apply'
      preLoaderRoute: typeof HooksActionsApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/admin/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/s/$slug/orders/$orderId': {
      id: '/s/$slug/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/s/$slug/orders/$orderId'
      preLoaderRoute: typeof SSlugOrdersOrderIdRouteImport
      parentRoute: typeof SSlugRoute
    }
    '/_authenticated/admin/tenants/$tenantId': {
      id: '/_authenticated/admin/tenants/$tenantId'
      path: '/$tenantId'
      fullPath: '/admin/tenants/$tenantId'
      preLoaderRoute: typeof AuthenticatedAdminTenantsTenantIdRouteImport
      parentRoute: typeof AuthenticatedAdminTenantsRoute
    }
  }
}

interface AuthenticatedAdminTenantsRouteChildren {
  AuthenticatedAdminTenantsTenantIdRoute: typeof AuthenticatedAdminTenantsTenantIdRoute
}

const AuthenticatedAdminTenantsRouteChildren: AuthenticatedAdminTenantsRouteChildren =
  {
    AuthenticatedAdminTenantsTenantIdRoute:
      AuthenticatedAdminTenantsTenantIdRoute,
  }

const AuthenticatedAdminTenantsRouteWithChildren =
  AuthenticatedAdminTenantsRoute._addFileChildren(
    AuthenticatedAdminTenantsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedBrandRoute: typeof AuthenticatedBrandRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedAdminTenantsRoute: typeof AuthenticatedAdminTenantsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBrandRoute: AuthenticatedBrandRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedAdminTenantsRoute: AuthenticatedAdminTenantsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SSlugRouteChildren {
  SSlugOrdersOrderIdRoute: typeof SSlugOrdersOrderIdRoute
}

const SSlugRouteChildren: SSlugRouteChildren = {
  SSlugOrdersOrderIdRoute: SSlugOrdersOrderIdRoute,
}

const SSlugRouteWithChildren = SSlugRoute._addFileChildren(SSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AgentsRoute: AgentsRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  SignupRoute: SignupRoute,
  HooksIngestRoute: HooksIngestRoute,
  SSlugRoute: SSlugRouteWithChildren,
  HooksActionsApplyRoute: HooksActionsApplyRoute,
  HooksAgentsAnomalyDetectorRoute: HooksAgentsAnomalyDetectorRoute,
  HooksAgentsAovLeakRoute: HooksAgentsAovLeakRoute,
  HooksAgentsAovOptimizerRoute: HooksAgentsAovOptimizerRoute,
  HooksAgentsAttributionRoute: HooksAgentsAttributionRoute,
  HooksAgentsBotQualityRoute: HooksAgentsBotQualityRoute,
  HooksAgentsBrowseAbandonmentRoute: HooksAgentsBrowseAbandonmentRoute,
  HooksAgentsBundleRecommenderRoute: HooksAgentsBundleRecommenderRoute,
  HooksAgentsCartRecoveryRoute: HooksAgentsCartRecoveryRoute,
  HooksAgentsChurnRiskRoute: HooksAgentsChurnRiskRoute,
  HooksAgentsCohortEngineRoute: HooksAgentsCohortEngineRoute,
  HooksAgentsCronAllRoute: HooksAgentsCronAllRoute,
  HooksAgentsDiscountElasticityRoute: HooksAgentsDiscountElasticityRoute,
  HooksAgentsFeedbackLoopRoute: HooksAgentsFeedbackLoopRoute,
  HooksAgentsFeedbackLoopAllRoute: HooksAgentsFeedbackLoopAllRoute,
  HooksAgentsFunnelHealerRoute: HooksAgentsFunnelHealerRoute,
  HooksAgentsLtvPredictorRoute: HooksAgentsLtvPredictorRoute,
  HooksAgentsMarginOptimizerRoute: HooksAgentsMarginOptimizerRoute,
  HooksAgentsMemoryFeedbackRoute: HooksAgentsMemoryFeedbackRoute,
  HooksAgentsMorningBriefRoute: HooksAgentsMorningBriefRoute,
  HooksAgentsOnboardingRoute: HooksAgentsOnboardingRoute,
  HooksAgentsPredictivePricingRoute: HooksAgentsPredictivePricingRoute,
  HooksAgentsPriceOptimizerRoute: HooksAgentsPriceOptimizerRoute,
  HooksAgentsPriceRevertRoute: HooksAgentsPriceRevertRoute,
  HooksAgentsPromoFatigueRoute: HooksAgentsPromoFatigueRoute,
  HooksAgentsPromoPortfolioRoute: HooksAgentsPromoPortfolioRoute,
  HooksAgentsRunAllRoute: HooksAgentsRunAllRoute,
  HooksAgentsSalesBotRoute: HooksAgentsSalesBotRoute,
  HooksAgentsSalesBotAllRoute: HooksAgentsSalesBotAllRoute,
  HooksAgentsSearchGapRoute: HooksAgentsSearchGapRoute,
  HooksAgentsSecondOrderNurtureRoute: HooksAgentsSecondOrderNurtureRoute,
  HooksAgentsSegmentationRoute: HooksAgentsSegmentationRoute,
  HooksAgentsStockoutRoute: HooksAgentsStockoutRoute,
  HooksAgentsTickRoute: HooksAgentsTickRoute,
  HooksDemoSeedRoute: HooksDemoSeedRoute,
  HooksEnginesAbandonedCartRoute: HooksEnginesAbandonedCartRoute,
  HooksEnginesAbandonedCartAllRoute: HooksEnginesAbandonedCartAllRoute,
  HooksEnginesDispatchRoute: HooksEnginesDispatchRoute,
  HooksEnginesReorderRoute: HooksEnginesReorderRoute,
  HooksEnginesReorderAllRoute: HooksEnginesReorderAllRoute,
  HooksEnginesWinbackRoute: HooksEnginesWinbackRoute,
  HooksEnginesWinbackAllRoute: HooksEnginesWinbackAllRoute,
  HooksEnginesWinbackOneRoute: HooksEnginesWinbackOneRoute,
  HooksTelegramPollRoute: HooksTelegramPollRoute,
  TrackSlugJsRoute: TrackSlugJsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
