-- Розширити event_type enum усіма типами, які присилають клієнти.
-- Адаптивна модель: MARQ приймає будь-яку подію, агенти самі визначають,
-- чи є достатньо даних для запуску.

ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'page_viewed';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'product_clicked';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'remove_from_cart';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'cart_viewed';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'begin_checkout';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'checkout_clicked';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'checkout_viewed';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'checkout_abandoned';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'checkout_failed';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'offer_shown';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'offer_skipped';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'upsell_accepted';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'upsell_dismissed';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'exit_intent_shown';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'exit_intent_dismissed';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'exit_intent_converted';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'bot_started';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'search_performed';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'wishlist_added';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'wishlist_removed';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'review_submitted';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'promo_applied';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'promo_failed';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'share_clicked';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'phone_call_clicked';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'telegram_link_clicked';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'chat_opened';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'chat_message_sent';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'newsletter_signup';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'ai_chat_product_click';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'ai_chat_product_recommended';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'reorder_completed';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'app_opened';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'deep_link_opened';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'push_received';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'push_opened';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'oauth_callback_success';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'apk_install_prompt_shown';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'apk_install_prompt_clicked';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'apk_install_prompt_dismissed';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'bot_reorder_reminder_sent';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'referral_link_copied';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'referral_link_shared';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'referral_clicked';
ALTER TYPE public.event_type ADD VALUE IF NOT EXISTS 'referral_rewarded';