INSERT INTO content_pages (id, tenant_id, slug, title, content_type, body_md, seo_title, seo_description, is_published, published_at, metadata) VALUES
('b58c55ae-db77-46d5-b927-4cb43d10d429','abec86dc-dfa9-4cde-adc3-c813b7ec455f','chomu-sushena-yalovychyna-krashcha-za-konservy','Чому сушена яловичина краща за консерви для собак: 7 науково обґрунтованих причин','blog','Сушена яловичина зберігає до 92% поживних речовин, на відміну від консервів. У 100 г сушеної яловичини — 65-75 г чистого білка проти 18-22 г у консервах. Без консервантів, з користю для зубів, гіпоалергенна. Дозування: цуценята до 5%, дорослі до 10% денного раціону.','Чому сушена яловичина краща за консерви для собак','Сушена яловичина зберігає білок, не містить консервантів, корисна для зубів. Гайд від BASIC.FOOD.',true,'2026-04-18T05:34:23.603178+00:00','{"category":"dog-nutrition","author_name":"BASIC.FOOD","keywords":["сушена яловичина","консерви для собак","натуральні ласощі"],"source":"basicfood"}'::jsonb),
('bafd5ede-95b8-45b2-a25c-b40e6dcfe026','abec86dc-dfa9-4cde-adc3-c813b7ec455f','yak-vybraty-laschi-dlya-dresyruvannya-sobaky','Як вибрати ласощі для дресирування собаки: повний гайд','blog','Позитивне підкріплення прискорює навчання на 67%. 5 критеріїв ласощів: маленький розмір (1-2 см), висока цінність (high-value), натуральний склад, низька калорійність (до 10% раціону), без зернових. Топ-3: легені, серце, печінка.','Як вибрати ласощі для дресирування собаки','5 критеріїв вибору training treats для собак: розмір, цінність, склад. Поради кінологів.',true,'2026-04-18T05:34:23.603178+00:00','{"category":"training","author_name":"BASIC.FOOD","keywords":["ласощі для дресирування","training treats"],"source":"basicfood"}'::jsonb),
('f1933ce5-752f-4257-99ba-c5254444e87b','abec86dc-dfa9-4cde-adc3-c813b7ec455f','chym-pidhoduvaty-tsutsenya-natural-ni-laschi','Чим підгодовувати цуценя: натуральні ласощі від 4 місяців','blog','Цуценя від 4 місяців може отримувати ласощі. Безпечні види м''яса: легені, серце, печінка маленькими шматочками. Доза: до 5% денного раціону. Уникати: великих шматків, солі, спецій. Поступове введення — 1 новий вид на тиждень.','Чим підгодовувати цуценя: натуральні ласощі','Як вводити натуральні ласощі цуценяті від 4 міс. Безпечні види м''яса і доза.',true,'2026-04-18T05:34:23.603178+00:00','{"category":"pet-health","author_name":"BASIC.FOOD","keywords":["ласощі для цуценят","puppy treats"],"source":"basicfood"}'::jsonb),
('1daa8b19-bd2d-471d-8b15-0cc0aed7d631','abec86dc-dfa9-4cde-adc3-c813b7ec455f','natural-ni-laschi-dlya-kotiv-shcho-vybraty','Натуральні ласощі для котів: що вибрати і чому це важливо','blog','Коти — облігатні хижаки, потребують 70% тваринного білка. Сушене м''ясо ідеально: чистий білок, таурин, без вуглеводів. Топ для котів: курячі шиї (маленькі), легені (м''які), печінка (для смаку). Доза: 5-10 г на день.','Натуральні ласощі для котів','Сушене м''ясо для котів: курячі шиї, легені, печінка. Чистий білок без хімії.',true,'2026-04-18T05:34:23.603178+00:00','{"category":"pet-health","author_name":"BASIC.FOOD","keywords":["ласощі для котів","cat treats"],"source":"basicfood"}'::jsonb),
('1ebb67d5-73a7-480a-a459-d223888169ba','abec86dc-dfa9-4cde-adc3-c813b7ec455f','chym-korysni-vnutrishni-orhany-pry-ratsioni-tvaryny','Чим корисні внутрішні органи (субпродукти) у раціоні тварини','blog','Серце — таурин, B12, коензим Q10. Печінка — вітаміни A, D, K, залізо, мідь. Нирки — селен, B-вітаміни. Легені — низькокалорійні, ідеальні для дресури. Доза субпродуктів: 10-15% м''ясного раціону, печінки — не більше 5%.','Користь субпродуктів у раціоні собаки і кота','Серце, печінка, нирки — концентроване джерело вітамінів і амінокислот для тварин.',true,'2026-04-18T05:34:23.603178+00:00','{"category":"pet-health","author_name":"BASIC.FOOD","keywords":["субпродукти","BARF","сушене серце","сушена печінка"],"source":"basicfood"}'::jsonb),
('eee57ca9-2f6c-4b6a-8d1a-bc164926a570','abec86dc-dfa9-4cde-adc3-c813b7ec455f','de-kupyty-sushenu-yalovychynu-dlya-sobaky-rivne','Де купити сушену яловичину для собаки в Рівному: 3 способи','blog','3 способи замовлення BASIC.FOOD: 1) Сайт basicfood.lovable.app — повний каталог, оплата онлайн. 2) Telegram-бот — швидке замовлення в чаті, push-сповіщення. 3) Viber — особистий менеджер. Доставка Новою Поштою 1-2 дні по Україні.','Де купити сушену яловичину для собаки в Рівному','Замовляйте натуральні ласощі BASIC.FOOD онлайн, у Telegram або Viber. Доставка по Україні.',true,'2026-04-18T16:09:14.541129+00:00','{"category":"general","author_name":"BASIC.FOOD","keywords":["BASIC.FOOD Рівне","Telegram бот","сушена яловичина Україна"],"source":"basicfood"}'::jsonb),
('04277e98-ce4d-4698-a2b4-06290a675961','abec86dc-dfa9-4cde-adc3-c813b7ec455f','shche-blyzhche-do-vlasnykiv-instagram-telegram-viber','Як ми спілкуємось з власниками собак: Instagram, Telegram-бот і Viber','blog','5 каналів зв''язку BASIC.FOOD: Instagram (@basic.rivne) — щоденні історії і фото. Telegram-бот — миттєві замовлення, статус доставки. Viber — особисті консультації. Email — деталі та чеки. Сайт — каталог і блог.','Контакти BASIC.FOOD: Instagram, Telegram, Viber','5 каналів спілкування з командою BASIC.FOOD — оберіть зручний формат.',true,'2026-04-18T16:09:14.541129+00:00','{"category":"general","author_name":"BASIC.FOOD","keywords":["BASIC.FOOD контакти","Instagram basic.rivne","Telegram бот"],"source":"basicfood"}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  body_md = EXCLUDED.body_md,
  seo_title = EXCLUDED.seo_title,
  seo_description = EXCLUDED.seo_description,
  is_published = EXCLUDED.is_published,
  published_at = EXCLUDED.published_at,
  metadata = EXCLUDED.metadata,
  updated_at = now();